name: build_linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/checkout@v4
      #   with:
      #     repository: ogdf/ogdf
      #     path: ogdf

      - name: cache OGDF built
        id: cache-ogdf
        uses: actions/cache@v3
        with:
          path:  ogdf-conda/src/lib
          key: ${{ runner.os }}-ogdf

      - name: build ogdf
        if: steps.cache-ogdf.outputs.cache-hit != 'true'
        run: |
          cd ogdf-conda/src
          cmake -DBUILD_SHARED_LIBS=ON .
          make
          mkdir lib
          mv *.so lib

      - name: build tmap
        run: |
          LIBOGDF_INSTALL_PATH=ogdf-conda/src cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=out .
          make
          ls -ltrh out

      - name: make zip of binaries
        run: |
          zip binaries-${{ runner.os }}.zip ogdf-conda/src/lib/* out/*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true
          name: "0.1"

      - name: Debug with tmate on failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3
