name: build_windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/checkout@v4
      #   with:
      #     repository: ogdf/ogdf
      #     path: ogdf

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            git
            zip

      - name: cache OGDF built
        id: cache-ogdf
        uses: actions/cache@v3
        with:
          path:  ogdf-conda/src/lib
          key: ${{ runner.os }}-ogdf

      - name: build ogdf
        if: steps.cache-ogdf.outputs.cache-hit != 'true'
        run: |
          cd ogdf-conda/src
          cmake -G "Visual Studio 17 2022" -A x64 -T ClangCL .
          make
          mkdir lib
          mv *.dll lib

      - name: build tmap
        run: |
          LIBOGDF_INSTALL_PATH=ogdf-conda/src cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=out -G "Visual Studio 17 2022" -A x64 -T ClangCL .
          make
          ls -ltrh *.dll

      - name: make zip of binaries
        run: |
          zip binaries-${{ runner.os }}.zip ogdf-conda/src/lib *.dll

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true
          name: "0.1"

      - name: Debug with tmate on failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3
