name: build_osx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/checkout@v4
      #   with:
      #     repository: ogdf/ogdf
      #     path: ogdf

      - name: build ogdf
        run: |
          cd ogdf-conda/src
          cmake -DBUILD_SHARED_LIBS=ON .
          make
          mkdir lib
          mv *.dylib lib

      - name: build tmap
        run: |
          brew install libomp
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          LIBOGDF_INSTALL_PATH=ogdf-conda/src cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=out .
          make
          ls -ltrh out

      - name: make zip of binaries
        run: |
          zip binaries-${{ runner.os }}.zip ogdf-conda/src/lib/* out/*

      - uses: softprops/action-gh-release@v1
        with:
          files: *.zip
          tag_name: "0.1"
          
      - name: Debug with tmate on failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3
