name: build_windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: clang64
          install: >-
            base-devel
            mingw-w64-clang-x86_64-toolchain
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-openmp
            mingw-w64-clang-x86_64-ninja
            git
            zip

      - name: build ogdf
        run: |
          cd ogdf-conda/src
          cmake -DBUILD_SHARED_LIBS=ON -G "Ninja" .
          cmake --build .
          mkdir lib
          cp *.dll* lib || true
          cp *.lib lib || true
          find . \( -iname '*.dll*' -o -iname '*.lib*' \) -exec ls -ltrh {} \;

      - name: build tmap
        run: |
          LIBOGDF_INSTALL_PATH=ogdf-conda/src cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=out -G "Ninja" .
          cmake --build .
          find . \( -iname '*.dll*' -o -iname '*.lib*' \) -exec ls -ltrh {} \;

      - name: check tmap exports "LayoutFromEdgeList" function
        run: |
          objdump -p libtmap.dll | grep -i layoutfrom || true

      - name: make zip of binaries
        run: |
          zip -j binaries-${{ runner.os }}.zip ogdf-conda/src/lib/* *.dll*

      - uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          tag_name: "0.1"

      - name: Debug with tmate on failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3
