name: build_windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/checkout@v4
      #   with:
      #     repository: ogdf/ogdf
      #     path: ogdf

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            git
            zip

      - name: build ogdf
        run: |
          cd ogdf-conda/src
          # cmake -G "MSYS Makefiles" -DBUILD_SHARED_LIBS=ON .
          cmake -G "MSYS Makefiles" .
          cmake --build .
          mkdir lib
          # mv *.dll lib
          mv lib*.a lib

      - name: build tmap
        run: |
          LIBOGDF_INSTALL_PATH=ogdf-conda/src cmake -G "MSYS Makefiles" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=out cmake .
          cmake --build .
          ls -ltrh *.dll

      - name: make zip of binaries
        run: |
          zip binaries-${{ runner.os }}.zip ogdf-conda/src/lib/* *.dll

      - uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          tag_name: "0.1"

      - name: Debug with tmate on failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3
