name: build_windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/checkout@v4
      #   with:
      #     repository: ogdf/ogdf
      #     path: ogdf

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            git
            zip

      - name: build ogdf
        run: |
          cd ogdf-conda/src
          cmake -DBUILD_SHARED_LIBS=ON -G "Visual Studio 17 2022" -A x64 -T ClangCL .
          cmake --build .
          ln -s Debug/ lib

      - name: build tmap
        run: |
          LIBOGDF_INSTALL_PATH=ogdf-conda/src cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=out -G "Visual Studio 17 2022" -A x64 -T ClangCL .
          cmake --build .
          ls -ltrh Debug/*

      - name: make zip of binaries
        run: |
          zip -j binaries-${{ runner.os }}.zip ogdf-conda/src/lib/* Debug/*.dll

      - uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          tag_name: "0.1"

      - name: Debug with tmate on failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3
